### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by bunger20** [bellosil21/pokerTexasHoldEm#1]
Steps to recreate:
1. Launch game. 
2. Press Start Game button quickly. 
3. The card images will not appear, which is important for actually being able to play.

**Comment by marcial21** [comment]
Thank you for the input. We have discovered the cause of this and will be added on our to do list.

**Comment by hojo21** [comment]
We fixed this issue by modifying the local game. The cards will now show up immediately.

**Comment by hoser21** [comment]
It appears that this issue was not fully fixed when we added the change to the Game Framework as directed by the professor. On rare occasions when the game is started immediately after launching our app, the GUI will not load properly. I believe it may be a Game Framework problem since the full functionality of our game works when the GUI loads. If the player waits about 10 seconds before starting the game, the GUI is more likely to load on game start and play as desired.

**Comment by hoser21** [comment]
We will not be fixing this bug.

**Comment by bunger20** [comment]
Cool. Ten seconds isn't a horrible wait time :)
