### ISSUE TITLE
player Number Issue

### ISSUE THREAD

**Issue by SydneyWells** [bellosil21/pokerTexasHoldEm#2]
Steps to recreate:
1. Remove player from config screen
2. Run game 

...
N. If you run the game with fewer than 4 players, the game resources don't render and the game doesn't assign the player attributes correctly- instead of computer player 1, 2, etc; we see players 1-4. So it looks weird and also is unplayable.

**Comment by LozinALaifer** [comment]
Good to hear. We'll look into the problem and fix the problem for the beta release.

**Comment by hoser21** [comment]
This functionally is now fixed in the latest version. Our game can play with a configuration of 2, 3, and 4 players.

**Comment by SydneyWells** [comment]
I verified that the game can play with fewer than 4 players, but it does still show the players who are not part of the game- there is a blank profile for the extra players.
